<?php

namespace AppBundle\Repository;

/**
 * DokumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DokumentRepository extends \Doctrine\ORM\EntityRepository
{
}
